### PR TITLE
Better defaults

### PR DESCRIPTION
**Pull request by i1i1**
This pr is a messy a bit, because it does everything. Better look at individual commits.

Overall, it started off with removing unnecessary defaults in the first commit and better export of nixos modules in the second one.

Latter commits are misc, they just do formatting of nix files and add pre commit hooks (with default `nix develop` environment) with linting (you can also lint and check formatting with `nix flake check` now).

I can split the first 2 commits and latter ones in separate pull request if you want, but I just found it easier for now.

### CODE REVIEW

**Comment by alex-morgun** [comment]
Hard to tell what actually changed and what improvements are.

**Comment by i1i1** [comment]
> Hard to tell what actually changed and what improvements are.

Take a look at each individual commit.

> Why are these defaults are better?

Fair enough! I've
- moved system packages setting to `configuration.nix` (previously `user-group.nix`)
- Removed enabling openssh by default
- make everything overwritable with `lib.mkDefault`

**Comment by alex-morgun** [comment]
I have an idea how to do the improvements easy to review way

1. Make a PR with this alone

> Latter commits are misc, they just do formatting of nix files and add pre commit hooks (with default nix develop environment) with linting (you can also lint and check formatting with nix flake check now).

2. Another PR with mkDefault
3. Another for user/group, but personally I like the original variant

**Comment by i1i1** [comment]
> I have an idea how to do the improvements easy to review way

I think it is quite easy to follow this pr commit by commit. Most of the changes are minor anyway. This pr is mostly yak shaving.

**Comment by ryan4yin** [comment]
pre-commit-hook is a good thing, could you please submit the two changes of pre-commit-hook addition and code formatting / linting respectively? 
In addition, I personally prefer `alejandra` to `nixpkgs-fmt`, could you replace this part?

**Comment by ryan4yin** [comment]
1. And another PR for `Export nixos modules` & flake-utils.
2. Another PR with some minor changes(mkDefault/Sanitize special argument)
3. As for user/group, I agreed with @alex-morgun , just keep it unmodified.

**Comment by ryan4yin** [comment]
> Sanitizing special argument does feel related to exporting nixos modules. Btw, maybe you know some way to not require users to pass special arguments at all?

I'm a little confused with this commit, I'll take a look at this one after other PRs getting merged.

> Also, am I getting it right that you want to have 3 prs as follows:
> 
>     * Export nixos modules & flake-utils
> 
>     * `pre-commit-hook` and code formatting
> 
>     * Other minor changes

Yep, I hope to merge these PR one by one, and then see what else needs to be done(NixOS 23.11, latest Linux mainline kernel, etc...).

**Comment by i1i1** [comment]
Closing in favor of #15 #16 #17

**Pull request closed without merging**
