### PR TITLE
docs: uefi - install nixos into SSD / eMMC

### LINKED ISSUE #50: So... How does one actually install NixOS on the emmc?
That is a glaring omission in the documentation. It says "just follow the official NixOS documentation", but by doing that, you end up with an unbootable system (stuck at "EFI stub: Exiting boot services...").

### PR DESCRIPTION
**Pull request by ryan4yin**
Fix #50

### CODE REVIEW

**Comment by ryan4yin** [comment]
@zilti Does this installation process work for you?

**Comment by zilti** [comment]
Thank you for the effort, it is really appreciated, but - I don't know if it does work for me or not. Because I have absolutely no intention to currently either learn or use colmena just to install NixOS.

**Comment by ryan4yin** [comment]
@zilti The use of "colmena" is not a strict requirement in this context. You can also opt for "nixos-rebuild" as a method to deploy the system. You can refer to [HeroBrine1st/flake] as a practical example.

However, it's important to note that this project is geared towards users who already have a good grasp of NixOS. Offering a detailed, beginner-friendly guide that explains every aspect is not within the current goals of this project.

That being said, contributions are always appreciated, so feel free to submit PRs!

[HeroBrine1st/flake]: https://github.com/HeroBrine1st/flake

**Comment by zilti** [comment]
I do have a decent grasp of NixOS, using plain Nix, but also flakes and home-manager for my setup, and disko for partitioning. "Look at that random user's personal config" is not documentation. There is a massively wide gap between that and a "detailed, beginner-friendly guide that explains every aspect".

Good luck with the project!

**Comment by ryan4yin** [comment]
> I do have a decent grasp of NixOS, using plain Nix, but also flakes and home-manager for my setup, and disko for partitioning.

Then convert the colmena demo to a nixos-rebuild one should not be a problem for you.

> "Look at that random user's personal config" is not documentation. There is a massively wide gap between that and a "detailed, beginner-friendly guide that explains every aspect".

I mean we have no doc for this currently,  but you can submit a PR for this if you find it troublesome.
 
> Good luck with the project!

I apologize for this if you find my words not friendly, I'm not a native speaker...

**Pull request merged**
