### PR TITLE
chore: update `nixpkgs` to `24.05`

### PR DESCRIPTION
**Pull request by Naxdy**

### CODE REVIEW

**Comment by HeroBrine1st** [comment]
I once tried to make this flake follow nixpkgs from my flake and got unexpected kernel rebuild. It is unexpected to me because kernel has literally no dependencies on other derivates and no source files changed, so that kernel rebuild isn't needed. Probably.

Fixed-output derivation is a possible fix, but I don't think kernel build is fully reproducible.

**Comment by Naxdy** [comment]
Well, the kernel still has to be built _with_ something. So if something with regards to the toolchain changes, it makes sense that the kernel will be rebuilt, if I understand it correctly.

The update to latest stable nixpkgs is also going to be important once we hit 24.11, since there the option `hardware.opengl` has been renamed to `hardware.graphics`. But I suppose it could also be deferred until then.

**Comment by HeroBrine1st** [comment]
Yes, I forgot about hardware.graphics. It is inevitable.

Regarding kernel build - it is just too long, ~3 hours for me under old PC cooler. But we have specialArgs for kernel toolchain nixpkgs, so it is not an issue altogether :-) it can be locked to whatever it needs. Completely forgot about that.

**Comment by Naxdy** [comment]
Yep, `specialArgs` is perfect for this. Another issue is that `panfork` has been taken down and is no longer maintained, so we'll have to switch to upstream mesa pertty soon, which does have panfrost support now. Not sure how panfrost support has evolved from 24.0.x to 24.2.x, so that move may happen now, or for nixos 24.11.

**Pull request merged**
